In [58]:
import pandas as pd

In [59]:
df = pd.read_csv("../datasets/housing.csv",usecols=['housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'])

In [60]:
df.shape

(20640, 7)

In [61]:
df.head()

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
2,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0
3,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0
4,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0

In [62]:
df = df.dropna()

In [63]:
y = df.iloc[:,-1]
X = df.iloc[:,:-1]

In [64]:
X

,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
0,41.0,880.0,129.0,322.0,126.0,8.3252
1,21.0,7099.0,1106.0,2401.0,1138.0,8.3014
2,52.0,1467.0,190.0,496.0,177.0,7.2574
3,52.0,1274.0,235.0,558.0,219.0,5.6431
4,52.0,1627.0,280.0,565.0,259.0,3.8462
...,...,...,...,...,...,...
20635,25.0,1665.0,374.0,845.0,330.0,1.5603
20636,18.0,697.0,150.0,356.0,114.0,2.5568
20637,17.0,2254.0,485.0,1007.0,433.0,1.7000
20638,18.0,1860.0,409.0,741.0,349.0,1.8672
20639,16.0,2785.0,616.0,1387.0,530.0,2.3886

In [65]:
y

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20433, dtype: float64

In [66]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=28)

In [67]:
#Will try all four, Linear Regression, Ridge, Lasso, ElasticNet

In [68]:
#LR
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.5384580968148323

In [ ]:
#Ridge
from sklearn.linear_model import Ridge
r = Ridge(alpha=0.1)
r.fit(X_train,y_train)
y_pred = r.predict(X_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.5384580983513836

In [73]:
#Lasso
from sklearn.linear_model import Lasso
l = Lasso(alpha=0.1)
l.fit(X_train,y_train)
y_pred = l.predict(X_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.538458104929203

In [ ]:
#ElasticNet
from sklearn.linear_model import ElasticNet
El = ElasticNet(alpha=0.9,l1_ratio=0.9)
El.fit(X_train,y_train)
y_pred = El.predict(X_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.5381096431500514