In [41]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
from sklearn.model_selection import train_test_split

In [31]:
data = load_breast_cancer()

In [32]:
df = pd.DataFrame(data.data, columns=data.feature_names)

In [36]:
df['Target']= data.target

In [37]:
df['Target']

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: Target, Length: 569, dtype: int64

In [35]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [34]:
df.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [40]:
df.columns

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension',
       'Target'],
      dtype='object')

In [39]:
X = df.drop("Target",axis=1)
y = df['Target']

In [42]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=32)

In [43]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [44]:
gnb.fit(X_train,y_train)

GaussianNB()

In [45]:
y_pred = gnb.predict(X_test)

In [46]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9122807017543859

In [48]:
gnb.class_prior_

array([0.36923077, 0.63076923])

In [51]:
gnb.theta_
#Mean of every feature, 2 arrays, first for output 0 and other for output 1

array([[1.75155952e+01, 2.17367857e+01, 1.15792560e+02, 9.81457738e+02,
        1.03141488e-01, 1.47643333e-01, 1.62135714e-01, 8.83188095e-02,
        1.93832738e-01, 6.29943452e-02, 6.17405357e-01, 1.24686131e+00,
        4.38530357e+00, 7.28742262e+01, 6.86259524e-03, 3.35953929e-02,
        4.27330952e-02, 1.52087143e-02, 2.10605298e-02, 4.22598810e-03,
        2.11569643e+01, 2.94914881e+01, 1.41605060e+02, 1.41966131e+03,
        1.44307083e-01, 3.79413155e-01, 4.49283214e-01, 1.80869702e-01,
        3.24812500e-01, 9.22692262e-02],
       [1.20737282e+01, 1.77903484e+01, 7.75859582e+01, 4.56703833e+02,
        9.26387456e-02, 7.96353659e-02, 4.61282115e-02, 2.56147108e-02,
        1.74331359e-01, 6.30173868e-02, 2.78271429e-01, 1.20671394e+00,
        1.97337213e+00, 2.06170139e+01, 7.24026829e-03, 2.16415296e-02,
        2.64301415e-02, 9.94186063e-03, 2.04171080e-02, 3.63293415e-03,
        1.32967143e+01, 2.34067596e+01, 8.64762369e+01, 5.51409756e+02,
        1.25802648e-01, 1.84367422e-01, 1.68796348e-01, 7.49895157e-02,
        2.71239373e-01, 7.99446690e-02]])

In [54]:
pd.DataFrame(gnb.theta_,columns=X_train.columns,index=["Malignant","Benign"])

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
Malignant,17.515595,21.736786,115.792560,981.457738,0.103141,0.147643,0.162136,0.088319,0.193833,0.062994,...,21.156964,29.491488,141.605060,1419.661310,0.144307,0.379413,0.449283,0.18087,0.324812,0.092269
Benign,12.073728,17.790348,77.585958,456.703833,0.092639,0.079635,0.046128,0.025615,0.174331,0.063017,...,13.296714,23.406760,86.476237,551.409756,0.125803,0.184367,0.168796,0.07499,0.271239,0.079945

In [55]:
#This above table tells a lot. Like mean radius of a Malignant cell is 17.5 and for Benign it's 12

In [52]:
gnb.var_

array([[9.58914384e+00, 1.49417148e+01, 4.44964394e+02, 1.23179057e+05,
        4.62481912e-04, 3.41888830e-03, 6.07771005e-03, 1.49409053e-03,
        1.12736798e-03, 3.65406385e-04, 1.11123518e-01, 2.39108786e-01,
        6.29074014e+00, 3.01951223e+03, 3.15537825e-04, 6.88031537e-04,
        8.10746842e-04, 3.38289234e-04, 4.22295721e-04, 3.10853034e-04,
        1.66860784e+01, 3.15138283e+01, 7.89444244e+02, 3.11289009e+05,
        7.81683237e-04, 3.09048591e-02, 3.50345912e-02, 2.55886267e-03,
        6.41123294e-03, 8.11120156e-04],
       [2.96365875e+00, 1.59563499e+01, 1.29513188e+02, 1.65678174e+04,
        4.71814901e-04, 1.33535418e-03, 2.17344100e-03, 5.36138003e-04,
        9.16471335e-04, 3.51268700e-04, 1.16347930e-02, 3.50396489e-01,
        5.85575614e-01, 6.68912391e+01, 3.15615482e-04, 5.71708969e-04,
        1.51991228e-03, 3.39086178e-04, 3.51370850e-04, 3.14388407e-04,
        3.70206747e+00, 3.08871935e+01, 1.73858396e+02, 2.47193313e+04,
        6.91428645e-04, 8.99521289e-03, 2.11046593e-02, 1.48843186e-03,
        2.11924606e-03, 5.07344485e-04]])

In [56]:
pd.DataFrame(gnb.var_,columns=X_train.columns,index=["Malignant","Benign"])

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
Malignant,9.589144,14.941715,444.964394,123179.056675,0.000462,0.003419,0.006078,0.001494,0.001127,0.000365,...,16.686078,31.513828,789.444244,311289.009107,0.000782,0.030905,0.035035,0.002559,0.006411,0.000811
Benign,2.963659,15.956350,129.513188,16567.817399,0.000472,0.001335,0.002173,0.000536,0.000916,0.000351,...,3.702067,30.887194,173.858396,24719.331291,0.000691,0.008995,0.021105,0.001488,0.002119,0.000507

In [57]:
#Variance helps as the mean can sometimes be similar