In [103]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

In [104]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36"
}

In [105]:
url = 'https://pokemondb.net/pokedex/game/red-blue-yellow'

In [106]:
webpage = requests.get(url,headers=headers).text

In [107]:
soup = BeautifulSoup(webpage,'lxml')

In [108]:
soup.prettify()

'<!DOCTYPE html>\n<html lang="en">\n <head>\n  <meta charset="utf-8"/>\n  <title>\n   Pokémon Red/Blue/Yellow - Kanto Pokédex | Pokémon Database\n  </title>\n  <link href="https://img.pokemondb.net" rel="preconnect"/>\n  <link href="https://s.pokemondb.net" rel="preconnect"/>\n  <link as="font" crossorigin="" href="/static/fonts/fira-sans-v17-latin-400.woff2" rel="preload" type="font/woff2"/>\n  <link as="font" crossorigin="" href="/static/fonts/fira-sans-v17-latin-400i.woff2" rel="preload" type="font/woff2"/>\n  <link as="font" crossorigin="" href="/static/fonts/fira-sans-v17-latin-600.woff2" rel="preload" type="font/woff2"/>\n  <link href="/static/css/pokemondb-a8dfa469be.css" rel="stylesheet"/>\n  <meta content="width=device-width, initial-scale=1" name="viewport"/>\n  <meta content="The native Pokédex for Red/Blue/Yellow, listing all Pokémon from the Kanto region." name="description" property="og:description"/>\n  <link href="https://pokemondb.net/pokedex/game/red-blue-yellow" rel="canonical"/>\n  <meta content="https://pokemondb.net/pokedex/game/red-blue-yellow" property="og:url"/>\n  <meta content="https://img.pokemondb.net/images/featured/pokedex-rby.png" property="og:image"/>\n  <meta content="summary_large_image" name="twitter:card"/>\n  <meta content="max-image-preview:large" name="robots"/>\n  <meta content="Pokémon Red/Blue/Yellow - Kanto Pokédex" property="og:title"/>\n  <link href="/favicon.ico" rel="shortcut icon" type="image/x-icon"/>\n  <link href="/apple-touch-icon-precomposed.png" rel="apple-touch-icon-precomposed"/>\n  <link href="https://pokemondb.net/news/feed" rel="alternate" title="The Pokémon Database newsfeed" type="application/rss+xml"/>\n  <script>\n   var localDbVersions = 260529;\n  </script>\n  <script defer="" src="/static/js/global-7f496e2ea5.js">\n  </script>\n  <noscript>\n   <style>\n    .main-menu-item:hover > .main-menu-sub { visibility: visible; opacity: 1; }\n   </style>\n  </noscript>\n </head>\n <body>\n  <a class="sr-only" href="#main">\n   Skip to main content\n  </a>\n  <header class="main-header">\n   <div class="grid-container">\n    <a class="header-logo" href="/">\n     <picture>\n      <source height="100" media="(min-width: 900px)" srcset="https://img.pokemondb.net/design/avif/header-lg.avif" type="image/avif" width="1140">\n       <source height="100" media="(min-width: 620px)" srcset="https://img.pokemondb.net/design/avif/header-md.avif, https://img.pokemondb.net/design/avif/header-md-2x.avif 2x" type="image/avif" width="807">\n        <source height="100" srcset="https://img.pokemondb.net/design/avif/header-sm.avif, https://img.pokemondb.net/design/avif/header-sm-2x.avif 2x" type="image/avif" width="367">\n         <source height="100" media="(min-width: 900px)" srcset="https://img.pokemondb.net/design/header-lg.png" type="image/png" width="1140">\n          <source height="100" media="(min-width: 620px)" srcset="https://img.pokemondb.net/design/header-md.png, https://img.pokemondb.net/design/header-md-2x.png 2x" type="image/png" width="807">\n           <img alt="Pokemon Database logo, with Scizor" fetchpriority="high" src="https://img.pokemondb.net/design/header-sm.png" srcset="https://img.pokemondb.net/design/header-sm-2x.png 2x"/>\n          </source>\n         </source>\n        </source>\n       </source>\n      </source>\n     </picture>\n    </a>\n   </div>\n  </header>\n  <nav class="main-menu grid-container">\n   <ul class="main-menu-list">\n    <li class="main-menu-item">\n     <a class="main-menu-heading" href="/sitemap">\n      <svg aria-label="Pokeball icon" class="main-menu-icon img-fixed" height="24" role="img" viewbox="0 0 512 512" width="24" xmlns="http://www.w3.org/2000/svg">\n       <g fill="#a3a3a3">\n        <path d="M229.7 36.8A220.9 220.9 0 0 0 37.5 224.9l-.4 4.3h106.5l1.4-4.7a116.3 116.3 0 0 1 73-77.5 114.7 114.7 0 0 1 149 79l.9 3.2H475l-1.7-10.1A220 220 0 0 0 281 36.7c-12-1.4-39.3-1.4-51.2 0z">\n        </path>\n        <path d="M239.7 185a74 74 0 0 0-49.7 40.3 73 73 0 0 0 15.4 82.3 72.1 72.1 0 0 0 101.9-1.2 68.8 68.8 0 0 0 20.6-50.7 69.1 69.1 0 0 0-21-51.2 73.3 73.3 0 0 0-33-19c-7.6-2.1-26.4-2.3-34.2-.5z">\n        </path>\n        <path d="M37.5 286.3a220.5 220.5 0 0 0 436 4.5l1.5-8.9H367.9l-1 3.2a130 130 0 0 1-17.7 37.6 144 144 0 0 1-26.9 26.8 142 142 0 0 1-30.7 15.4 96.3 96.3 0 0 1-35.8 5.3 90 90 0 0 1-22.5-1.7 114 114 0 0 1-58.6-31.7 110.1 110.1 0 0 1-28.3-46l-2.9-8.9H37l.6 4.4h-.1z">\n        </path>\n       </g>\n      </svg>\n      <span class="main-menu-title">\n       Data\n      </span>\n      <span class="main-menu-title-long">\n       Pokémon data\n      </span>\n     </a>\n     <ul class="main-menu-sub">\n      <li>\n       <a href="/pokedex">\n        Pokédex\n       </a>\n      </li>\n      <li>\n       <a href="/move">\n        Moves\n       </a>\n      </li>\n      <li>\n       <a href="/type">\n        Type chart\n       </a>\n      </li>\n      <li>\n       <a href="/ability">\n        Abilities\n       </a>\n      </li>\n      <li>\n       <a href="/item">\n        Items\n       </a>\n      </li>\n      <li>\n       <a href="/evolution">\n        Evolution chains\n       </a>\n      </li>\n      <li>\n       <a href="/location">\n        Pokémon locations\n       </a>\n      </li>\n      <li>\n       <a href="/sprites">\n        Sprite gallery\n       </a>\n      </li>\n      <li class="main-menu-hr-title">\n       Quick links\n      </li>\n      <li>\n       <a href="/pokedex/national">\n        National Pokédex\n       </a>\n      </li>\n      <li>\n       <a href="/pokedex/all">\n        Pokémon list with stats\n       </a>\n      </li>\n      <li>\n       <a href="/pokedex/game/legends-arceus">\n        Legends: Arceus Pokédex\n       </a>\n      </li>\n      <li>\n       <a href="/pokedex/game/scarlet-violet">\n        Scarlet &amp; Violet Pokédex\n       </a>\n      </li>\n     </ul>\n    </li>\n    <li class="main-menu-item">\n     <a class="main-menu-heading" href="/sitemap">\n      <svg aria-label="Mechanics icon" class="main-menu-icon img-fixed" height="24" role="img" viewbox="0 0 512 512" width="24" xmlns="http://www.w3.org/2000/svg">\n       <path d="M479.5 297.5v-82l-50.3-8.4a156.5 156.5 0 0 0-16-38.3l30-40.8-57.7-58.8-42 29c-12-6.5-25-12.2-38.2-15.9L297 33h-82l-8.3 50.3a163 163 0 0 0-38.3 16l-41-29.1L68.8 128l29.9 41A184 184 0 0 0 82.8 208l-50.3 7.4v82l50.3 8.3a163 163 0 0 0 16 38.3l-30 41.7 57.6 57.6 42-29.7a184 184 0 0 0 39 15.8l8.4 49.5h82l8.3-50.4c13.1-3.7 26-9.3 38.3-15.8l41.9 29.8 57.6-57.8-29.7-42c6.4-12 12-24 15.8-38.1l49.3-7.4.2.2zM255.8 342c-47.5 0-85.7-38.3-85.7-85.7s39.1-85.7 85.7-85.7 85.8 38.3 85.8 85.7-38.3 85.7-85.8 85.7z" fill="#a3a3a3">\n       </path>\n      </svg>\n      <span class="main-menu-title">\n       Mechanics\n      </span>\n      <span class="main-menu-title-long">\n       Game mechanics\n      </span>\n     </a>\n     <ul class="main-menu-sub">\n      <li>\n       <a href="/mechanics/breeding">\n        Breeding &amp; egg groups\n       </a>\n      </li>\n      <li>\n       <a href="/mechanics/move-tutors">\n        Move Tutors\n       </a>\n      </li>\n      <li>\n       <a href="/type/dual">\n        Dual type chart\n       </a>\n      </li>\n      <li>\n       <a href="/ev">\n        Effort Values (EVs)\n       </a>\n      </li>\n      <li>\n       <a href="/mechanics/natures">\n        Natures\n       </a>\n      </li>\n      <li>\n       <a href="/mechanics/hidden">\n        IVs/Personality\n       </a>\n      </li>\n      <li class="main-menu-hr-title">\n       Useful tools\n      </li>\n      <li>\n       <a href="/tools/moveset-search">\n        Moveset searcher\n       </a>\n      </li>\n      <li>\n       <a href="/tools/type-coverage">\n        Type coverage checker\n       </a>\n      </li>\n      <li>\n       <a href="/tools/text-list">\n        Text list generator\n       </a>\n      </li>\n     </ul>\n    </li>\n    <li class="main-menu-item">\n     <a class="main-menu-heading" href="/sitemap">\n      <svg aria-label="Game controller icon" class="main-menu-icon img-fixed" height="24" role="img" viewbox="0 0 512 512" width="24" xmlns="http://www.w3.org/2000/svg">\n       <path d="M117.4 121.9c-104.8 14.6-152 142.6-82.2 222.9 48 55 131.9 62.7 187.2 17l4.6-3.8H285l4.6 3.7c55.3 45.8 139.3 38.2 187.2-17 70.2-80.6 22.4-208.6-83.1-222.9-14.8-2-261.9-2-276.2 0m42.8 52.8c2.2 2.2 2.2 2.7 2.5 29.4l.3 27.2h53.5l2.4 2.5c3.8 3.8 3.8 40.8 0 44.6l-2.4 2.4H163l-.3 27.2c-.4 35 2.2 31.7-25 31.7-27.3 0-24.7 3.3-25-31.7l-.4-27.2H59l-2.4-2.4c-3.9-3.8-3.9-40.8 0-44.6l2.4-2.5h53.4l.3-27c.4-35-1.8-32.4 26.3-32 18.3.1 19 .2 21.3 2.4m259.3 16.5a33.7 33.7 0 0 1 19.5 42.5 33.2 33.2 0 0 1-59 5.8c-16.4-26.6 9.7-58.4 39.5-48.3M352 259a33 33 0 0 1 3.7 60 32.7 32.7 0 0 1-48-27.3A32.9 32.9 0 0 1 352 259" fill="#a3a3a3" fill-rule="evenodd">\n       </path>\n      </svg>\n      <span class="main-menu-title">\n       Games\n      </span>\n      <span class="main-menu-title-long">\n       Pokémon games\n      </span>\n     </a>\n     <ul class="main-menu-sub">\n      <li>\n       <a href="/winds-waves">\n        Winds &amp; Waves\n       </a>\n      </li>\n      <li>\n       <a href="/go">\n        Pokémon GO\n       </a>\n      </li>\n      <li class="main-menu-hr">\n      </li>\n      <li>\n       <a href="/legends-z-a">\n        Legends: Z-A\n       </a>\n      </li>\n      <li>\n       <a href="/scarlet-violet">\n        Scarlet &amp; Violet\n       </a>\n      </li>\n      <li class="main-menu-hr">\n      </li>\n      <li>\n       <a href="/legends-arceus">\n        Legends: Arceus\n       </a>\n      </li>\n      <li>\n       <a href="/brilliant-diamond-shining-pearl">\n        Brilliant Diamond &amp; Shining Pearl\n       </a>\n      </li>\n      <li>\n       <a href="/sword-shield">\n        Sword &amp; Shield\n       </a>\n      </li>\n      <li class="main-menu-hr">\n      </li>\n      <li>\n       <a href="/lets-go-pikachu-eevee">\n        Let\'s Go Pikachu &amp; Let\'s Go Eevee\n       </a>\n      </li>\n      <li>\n       <a href="/ultra-sun-ultra-moon">\n        Ultra Sun &amp; Ultra Moon\n       </a>\n      </li>\n      <li>\n       <a href="/sun-moon">\n        Sun &amp; Moon\n       </a>\n      </li>\n      <li class="main-menu-hr">\n      </li>\n      <li>\n       <a href="/omega-ruby-alpha-sapphire">\n        Omega Ruby &amp; Alpha Sapphire\n       </a>\n      </li>\n      <li>\n       <a href="/x-y">\n        X &amp; Y\n       </a>\n      </li>\n      <li class="main-menu-hr">\n      </li>\n      <li>\n       <a href="/black-white-2">\n        Black 2 &amp; White 2\n       </a>\n      </li>\n      <li>\n       <a href="/black-white">\n        Black &amp; White\n       </a>\n      </li>\n      <li class="main-menu-hr">\n      </li>\n      <li>\n       <a href="/heartgold-soulsilver">\n        HeartGold &amp; SoulSilver\n       </a>\n      </li>\n      <li>\n       <a href="/platinum">\n        Platinum\n       </a>\n      </li>\n      <li>\n       <a href="/diamond-pearl">\n        Diamond &amp; Pearl\n       </a>\n      </li>\n      <li class="main-menu-hr">\n      </li>\n      <li>\n       <a href="/emerald">\n        Emerald\n       </a>\n      </li>\n      <li>\n       <a href="/firered-leafgreen">\n        FireRed &amp; LeafGreen\n       </a>\n      </li>\n      <li>\n       <a href="/ruby-sapphire">\n        Ruby &amp; Sapphire\n       </a>\n      </li>\n      <li class="main-menu-hr">\n      </li>\n      <li>\n       <a href="/crystal">\n        Crystal\n       </a>\n      </li>\n      <li>\n       <a href="/gold-silver">\n        Gold &amp; Silver\n       </a>\n      </li>\n      <li class="main-menu-hr">\n      </li>\n      <li>\n       <a href="/yellow">\n        Yellow\n       </a>\n      </li>\n      <li>\n       <a href="/red-blue">\n        Red &amp; Blue\n       </a>\n      </li>\n      <li class="main-menu-hr">\n      </li>\n      <li>\n       <a href="/spinoff">\n        Spin-off games\n       </a>\n      </li>\n     </ul>\n    </li>\n    <li class="main-menu-item">\n     <a class="main-menu-heading" href="/sitemap">\n      <svg aria-label="Chat icon" class="main-menu-icon img-fixed" height="24" role="img" viewbox="0 0 512 512" width="24" xmlns="http://www.w3.org/2000/svg">\n       <path d="M36.5 95v241.5a44.5 44.5 0 0 0 43.9 43.9h58.5v73.1a7.3 7.3 0 0 0 12.8 5l71-78.1h208.9a44.5 44.5 0 0 0 43.9-44V95a44.5 44.5 0 0 0-43.9-43.9H80.4a44.5 44.5 0 0 0-43.9 44zm292.7 117.1a29.3 29.3 0 1 1 58.6 0 29.3 29.3 0 0 1-58.6 0zm-102.5 0a29.3 29.3 0 1 1 58.6 0 29.3 29.3 0 0 1-58.6 0zm-102.4 0a29.3 29.3 0 1 1 58.6 0 29.3 29.3 0 0 1-58.6 0z" fill="#a3a3a3">\n       </path>\n      </svg>\n      <span class="main-menu-title">\n       Other\n      </span>\n      <span class="main-menu-title-long">\n       Community/Other\n      </span>\n     </a>\n     <ul class="main-menu-sub">\n      <li>\n       <a href="/pokebase/">\n        Pokémon Q&amp;A\n       </a>\n      </li>\n      <li>\n       <a href="/pokebase/rmt/">\n        Pokémon Rate My Team\n       </a>\n      </li>\n      <li>\n       <a href="/pokebase/chat">\n        Chat Room\n       </a>\n      </li>\n      <li>\n       <a href="/pokebase/meta/">\n        Meta (Suggestion Box)\n       </a>\n      </li>\n      <li class="main-menu-hr-title">\n       Other pages\n      </li>\n      <li>\n       <a href="/">\n        Pokémon News\n       </a>\n      </li>\n      <li>\n       <a href="/maps">\n        Maps/Puzzles\n       </a>\n      </li>\n      <li>\n       <a href="/etymology">\n        Pokémon name origins\n       </a>\n      </li>\n      <li>\n       <a href="/about">\n        About/Contact us\n       </a>\n      </li>\n     </ul>\n    </li>\n    <li class="main-menu-item main-menu-item-search">\n     <form action="/search" class="sitesearch-form" method="get">\n      <label class="sr-only" for="sitesearch">\n       Search\n      </label>\n      <input autocomplete="off" class="input-text sitesearch-input" id="sitesearch" name="q" placeholder="Search" tabindex="100" type="text"/>\n      <svg aria-label="Search" class="main-menu-icon img-fixed" height="20" role="img" viewbox="0 0 512 512" width="20" xmlns="http://www.w3.org/2000/svg">\n       <path d="M495.6 466.4L373.8 339.6a206 206 0 0 0 48.5-132.9C422.3 92.7 329.5 0 215.6 0S8.8 92.7 8.8 206.7s92.8 206.7 206.8 206.7c42.8 0 83.5-12.9 118.4-37.4l122.8 127.7a26.8 26.8 0 0 0 38.1.8 27 27 0 0 0 .7-38.1zm-280-412.5c84.2 0 152.8 68.6 152.8 152.8s-68.6 152.8-152.8 152.8S62.8 291 62.8 206.7 131.3 54 215.6 54z" fill="#a3a3a3">\n       </path>\n      </svg>\n      <div class="sitesearch-results">\n      </div>\n     </form>\n    </li>\n   </ul>\n  </nav>\n  <main class="main-content grid-container" id="main">\n   <h1>\n    Red, Blue &amp; Yellow Pokédex\n   </h1>\n   <div class="panel panel-intro">\n    <p>\n     The original games\n     <strong>\n      Pokémon Red, Pokémon Blue &amp; Pokémon Yellow\n     </strong>\n     have a Pokédex of 151 Pokémon in the Kanto region.\n    </p>\n    <p>\n     They\'re shown below with the sprites from those games. Stats can be viewed on the\n     <a href="/pokedex/stats/gen1">\n      Gen 1 Pokémon stats\n     </a>\n     page.\n    </p>\n   </div>\n   <div class="infocard-list infocard-list-pkmn-lg">\n    <div class="infocard">\n     <span class="infocard-lg-img">\n      <a href="/pokedex/bulbasaur">\n       <img alt="Bulbasaur" class="img-fixed img-sprite img-sprite-v1" loading="lazy" src="https://img.pokemondb.net/sprites/red-blue/normal/bulbasaur.png"/>\n      </a>\n     </span>\n     <span class="infocard-lg-data text-muted">\n      <small>\n       #001\n      </small>\n      <br/>\n      <a class="ent-name" href="/pokedex/bulbasaur">\n       Bulbasaur\n      </a>\n      <br/>\n      <small>\n       <a class="itype grass" href="/type/grass">\n        Grass\n       </a>\n       ·\n       <a class="itype poison" href="/type/poison">\n        Poison\n       </a>\n      </small>\n     </span>\n    </div>\n    <div class="infocard">\n     <span class="infocard-lg-img">\n      <a href="/pokedex/ivysaur">\n       <img alt="Ivysaur" class="img-fixed img-sprite img-sprite-v1" loading="lazy" src="https://img.pokemondb.net/sprites/red-blue/normal/ivysaur.png"/>\n      </a>\n     </span>\n     <span class="infocard-lg-data text-muted">\n      <small>\n       #002\n      </small>\n      <br/>\n      <a class="ent-name" href="/pokedex/ivysaur">\n       Ivysaur\n      </a>\n      <br/>\n      <small>\n       <a class="itype grass" href="/type/grass">\n        Grass\n       </a>\n       ·\n       <a class="itype poison" href="/type/poison">\n        Poison\n       </a>\n      </small>\n     </span>\n    </div>\n    <div class="infocard">\n     <span class="infocard-lg-img">\n      <a href="/pokedex/venusaur">\n       <img alt="Venusaur" class="img-fixed img-sprite img-sprite-v1" loading="lazy" src="https://img.pokemondb.net/sprites/red-blue/normal/venusaur.png"/>\n      </a>\n     </span>\n     <span class="infocard-lg-data text-muted">\n      <small>\n       #003\n      </small>\n      <br/>\n      <a class="ent-name" href="/pokedex/venusaur">\n       Venusaur\n      </a>\n      <br/>\n      <small>\n       <a class="itype grass" href="/type/grass">\n        Grass\n       </a>\n       ·\n       <a class="itype poison" href="/type/poison">\n        Poison\n       </a>\n      </small>\n     </span>\n    </div>\n    <div class="infocard">\n     <span class="infocard-lg-img">\n      <a href="/pokedex/charmander">\n       <img alt="Charmander" class="img-fixed img-sprite img-sprite-v1" loading="lazy" src="https://img.pokemondb.net/sprites/red-blue/normal/charmander.png"/>\n      </a>\n     </span>\n     <span class="infocard-lg-data text-muted">\n      <small>\n       #004\n      </small>\n      <br/>\n      <a class="ent-name" href="/pokedex/charmander">\n       Charmander\n      </a>\n      <br/>\n      <small>\n       <a class="itype fire" href="/type/fire">\n        Fire\n       </a>\n      </small>\n     </span>\n    </div>\n    <div class="infocard">\n     <span class="infocard-lg-img">\n      <a href="/pokedex/charmeleon">\n       <img alt="Charmeleon" class="img-fixed img-sprite img-sprite-v1" loading="lazy" src="https://img.pokemondb.net/sprites/red-blue/normal/charmeleon.png"/>\n      </a>\n     </span>\n     <span class="infocard-lg-data text-muted">\n      <small>\n       #005\n      </small>\n      <br/>\n      <a class="ent-name" href="/pokedex/charmeleon">\n       Charmeleon\n      </a>\n      <br/>\n      <small>\n       <a class="itype fire" href="/type/fire">\n        Fire\n       </a>\n      </small>\n     </span>\n    </div>\n    <div class="infocard">\n     <span class="infocard-lg-img">\n      <a href="/pokedex/charizard">\n       <img alt="Charizard" class="img-fixed img-sprite img-sprite-v1" loading="lazy" src="https://img.pokemondb.net/sprites/red-blue/normal/charizard.png"/>\n      </a>\n     </span>\n     <span class="infocard-lg-data text-muted">\n      <small>\n       #006\n      </small>\n      <br/>\n      <a class="ent-name" href="/pokedex/charizard">\n       Charizard\n      </a>\n      <br/>\n      <small>\n       <a class="itype fire" href="/type/fire">\n        Fire\n       </a>\n       ·\n       <a class="itype flying" href="/type/flying">\n        Flying\n       </a>\n      </small>\n     </span>\n    </div>\n    <div class="infocard">\n     <span class="infocard-lg-img">\n      <a href="/pokedex/squirtle">\n       <img alt="Squirtle" class="img-fixed img-sprite img-sprite-v1" loading="lazy" src="https://img.pokemondb.net/sprites/red-blue/normal/squirtle.png"/>\n      </a>\n     </span>\n     <span class="infocard-lg-data text-muted">\n      <small>\n       #007\n      </small>\n      <br/>\n      <a class="ent-name" href="/pokedex/squirtle">\n       Squirtle\n      </a>\n      <br/>\n      <small>\n       <a class="itype water" href="/type/water">\n        Water\n       </a>\n      </small>\n     </span>\n    </div>\n

In [109]:
name = []
type = []
for i in soup.find_all('div', class_="infocard"):
    name.append(i.find('a',class_="ent-name").text.strip())
    type.append([x.text.strip()for x in i.find_all ('a',class_="itype")])

In [110]:
name

['Bulbasaur',
 'Ivysaur',
 'Venusaur',
 'Charmander',
 'Charmeleon',
 'Charizard',
 'Squirtle',
 'Wartortle',
 'Blastoise',
 'Caterpie',
 'Metapod',
 'Butterfree',
 'Weedle',
 'Kakuna',
 'Beedrill',
 'Pidgey',
 'Pidgeotto',
 'Pidgeot',
 'Rattata',
 'Raticate',
 'Spearow',
 'Fearow',
 'Ekans',
 'Arbok',
 'Pikachu',
 'Raichu',
 'Sandshrew',
 'Sandslash',
 'Nidoran♀',
 'Nidorina',
 'Nidoqueen',
 'Nidoran♂',
 'Nidorino',
 'Nidoking',
 'Clefairy',
 'Clefable',
 'Vulpix',
 'Ninetales',
 'Jigglypuff',
 'Wigglytuff',
 'Zubat',
 'Golbat',
 'Oddish',
 'Gloom',
 'Vileplume',
 'Paras',
 'Parasect',
 'Venonat',
 'Venomoth',
 'Diglett',
 'Dugtrio',
 'Meowth',
 'Persian',
 'Psyduck',
 'Golduck',
 'Mankey',
 'Primeape',
 'Growlithe',
 'Arcanine',
 'Poliwag',
 'Poliwhirl',
 'Poliwrath',
 'Abra',
 'Kadabra',
 'Alakazam',
 'Machop',
 'Machoke',
 'Machamp',
 'Bellsprout',
 'Weepinbell',
 'Victreebel',
 'Tentacool',
 'Tentacruel',
 'Geodude',
 'Graveler',
 'Golem',
 'Ponyta',
 'Rapidash',
 'Slowpoke',
 'Slowbro',
 'Magnemite',
 'Magneton',
 "Farfetch'd",
 'Doduo',
 'Dodrio',
 'Seel',
 'Dewgong',
 'Grimer',
 'Muk',
 'Shellder',
 'Cloyster',
 'Gastly',
 'Haunter',
 'Gengar',
 'Onix',
 'Drowzee',
 'Hypno',
 'Krabby',
 'Kingler',
 'Voltorb',
 'Electrode',
 'Exeggcute',
 'Exeggutor',
 'Cubone',
 'Marowak',
 'Hitmonlee',
 'Hitmonchan',
 'Lickitung',
 'Koffing',
 'Weezing',
 'Rhyhorn',
 'Rhydon',
 'Chansey',
 'Tangela',
 'Kangaskhan',
 'Horsea',
 'Seadra',
 'Goldeen',
 'Seaking',
 'Staryu',
 'Starmie',
 'Mr. Mime',
 'Scyther',
 'Jynx',
 'Electabuzz',
 'Magmar',
 'Pinsir',
 'Tauros',
 'Magikarp',
 'Gyarados',
 'Lapras',
 'Ditto',
 'Eevee',
 'Vaporeon',
 'Jolteon',
 'Flareon',
 'Porygon',
 'Omanyte',
 'Omastar',
 'Kabuto',
 'Kabutops',
 'Aerodactyl',
 'Snorlax',
 'Articuno',
 'Zapdos',
 'Moltres',
 'Dratini',
 'Dragonair',
 'Dragonite',
 'Mewtwo',
 'Mew']

In [111]:
type

[['Grass', 'Poison'],
 ['Grass', 'Poison'],
 ['Grass', 'Poison'],
 ['Fire'],
 ['Fire'],
 ['Fire', 'Flying'],
 ['Water'],
 ['Water'],
 ['Water'],
 ['Bug'],
 ['Bug'],
 ['Bug', 'Flying'],
 ['Bug', 'Poison'],
 ['Bug', 'Poison'],
 ['Bug', 'Poison'],
 ['Normal', 'Flying'],
 ['Normal', 'Flying'],
 ['Normal', 'Flying'],
 ['Normal'],
 ['Normal'],
 ['Normal', 'Flying'],
 ['Normal', 'Flying'],
 ['Poison'],
 ['Poison'],
 ['Electric'],
 ['Electric'],
 ['Ground'],
 ['Ground'],
 ['Poison'],
 ['Poison'],
 ['Poison', 'Ground'],
 ['Poison'],
 ['Poison'],
 ['Poison', 'Ground'],
 ['Normal'],
 ['Normal'],
 ['Fire'],
 ['Fire'],
 ['Normal'],
 ['Normal'],
 ['Poison', 'Flying'],
 ['Poison', 'Flying'],
 ['Grass', 'Poison'],
 ['Grass', 'Poison'],
 ['Grass', 'Poison'],
 ['Bug', 'Grass'],
 ['Bug', 'Grass'],
 ['Bug', 'Poison'],
 ['Bug', 'Poison'],
 ['Ground'],
 ['Ground'],
 ['Normal'],
 ['Normal'],
 ['Water'],
 ['Water'],
 ['Fighting'],
 ['Fighting'],
 ['Fire'],
 ['Fire'],
 ['Water'],
 ['Water'],
 ['Water', 'Fighting'],
 ['Psychic'],
 ['Psychic'],
 ['Psychic'],
 ['Fighting'],
 ['Fighting'],
 ['Fighting'],
 ['Grass', 'Poison'],
 ['Grass', 'Poison'],
 ['Grass', 'Poison'],
 ['Water', 'Poison'],
 ['Water', 'Poison'],
 ['Rock', 'Ground'],
 ['Rock', 'Ground'],
 ['Rock', 'Ground'],
 ['Fire'],
 ['Fire'],
 ['Water', 'Psychic'],
 ['Water', 'Psychic'],
 ['Electric'],
 ['Electric'],
 ['Normal', 'Flying'],
 ['Normal', 'Flying'],
 ['Normal', 'Flying'],
 ['Water'],
 ['Water', 'Ice'],
 ['Poison'],
 ['Poison'],
 ['Water'],
 ['Water', 'Ice'],
 ['Ghost', 'Poison'],
 ['Ghost', 'Poison'],
 ['Ghost', 'Poison'],
 ['Rock', 'Ground'],
 ['Psychic'],
 ['Psychic'],
 ['Water'],
 ['Water'],
 ['Electric'],
 ['Electric'],
 ['Grass', 'Psychic'],
 ['Grass', 'Psychic'],
 ['Ground'],
 ['Ground'],
 ['Fighting'],
 ['Fighting'],
 ['Normal'],
 ['Poison'],
 ['Poison'],
 ['Ground', 'Rock'],
 ['Ground', 'Rock'],
 ['Normal'],
 ['Grass'],
 ['Normal'],
 ['Water'],
 ['Water'],
 ['Water'],
 ['Water'],
 ['Water'],
 ['Water', 'Psychic'],
 ['Psychic'],
 ['Bug', 'Flying'],
 ['Ice', 'Psychic'],
 ['Electric'],
 ['Fire'],
 ['Bug'],
 ['Normal'],
 ['Water'],
 ['Water', 'Flying'],
 ['Water', 'Ice'],
 ['Normal'],
 ['Normal'],
 ['Water'],
 ['Electric'],
 ['Fire'],
 ['Normal'],
 ['Rock', 'Water'],
 ['Rock', 'Water'],
 ['Rock', 'Water'],
 ['Rock', 'Water'],
 ['Rock', 'Flying'],
 ['Normal'],
 ['Ice', 'Flying'],
 ['Electric', 'Flying'],
 ['Fire', 'Flying'],
 ['Dragon'],
 ['Dragon'],
 ['Dragon', 'Flying'],
 ['Psychic'],
 ['Psychic']]

In [112]:
df = pd.DataFrame({'name':name,'type':type})

In [113]:
df

           name              type
0     Bulbasaur   [Grass, Poison]
1       Ivysaur   [Grass, Poison]
2      Venusaur   [Grass, Poison]
3    Charmander            [Fire]
4    Charmeleon            [Fire]
..          ...               ...
146     Dratini          [Dragon]
147   Dragonair          [Dragon]
148   Dragonite  [Dragon, Flying]
149      Mewtwo         [Psychic]
150         Mew         [Psychic]

[151 rows x 2 columns]

In [114]:
new_df = df['type'].apply('  .  '.join)

In [115]:
new_df

0       Grass  .  Poison
1       Grass  .  Poison
2       Grass  .  Poison
3                   Fire
4                   Fire
             ...
146               Dragon
147               Dragon
148    Dragon  .  Flying
149              Psychic
150              Psychic
Name: type, Length: 151, dtype: str

In [116]:
df3 = pd.DataFrame({'name':name,'type':new_df})

In [117]:
df3[['type1', 'type2']] = df3['type'].str.split(' . ', expand=True)

In [118]:
df3

           name               type    type1    type2
0     Bulbasaur   Grass  .  Poison   Grass    Poison
1       Ivysaur   Grass  .  Poison   Grass    Poison
2      Venusaur   Grass  .  Poison   Grass    Poison
3    Charmander               Fire     Fire      NaN
4    Charmeleon               Fire     Fire      NaN
..          ...                ...      ...      ...
146     Dratini             Dragon   Dragon      NaN
147   Dragonair             Dragon   Dragon      NaN
148   Dragonite  Dragon  .  Flying  Dragon    Flying
149      Mewtwo            Psychic  Psychic      NaN
150         Mew            Psychic  Psychic      NaN

[151 rows x 4 columns]

In [153]:
def color_type(val):
    color_types = {
        'Normal': '#A8A77A',
        'Fire': '#EE8130',
        'Water': '#6390F0',
        'Electric': '#F7D02C',
        'Grass': '#7AC74C',
        'Ice': '#96D9D6',
        'Fighting': '#C22E28',
        'Poison': '#A33EA1',
        'Ground': '#E2BF65',
        'Flying': '#A98FF3',
        'Psychic': '#F95587',
        'Bug': '#A6B91A',
        'Rock': '#B6A136',
        'Ghost': '#735797',
        'Dragon': '#6F35FC'
    }

    return f'''
       background-color: {color_types.get(val, "#FFFFFF")};

        color: black;

        font-family: monospace;

        font-weight: medium;

        border-radius: 0px;
    '''

In [154]:
df4 = pd.DataFrame({'name':name,'type1':df3['type1'],'type2':df3['type2']})

In [155]:
df4['type1'] = df4['type1'].str.strip()
df4['type2'] = df4['type2'].str.strip()
df4 = df4.fillna('   ')

In [181]:
df5 = df4.style.hide(axis='index').map(color_type, subset=['type1', 'type2']).set_table_styles(
[

{
    'selector': 'th,td',
    'props': [
        ('border', '1px solid black'),
        ('padding', '7px'),
        ('font-family', 'monospace')
    ]
},
{
    'selector': 'table',
    'props': [
        ('border-collapse', 'collapse'),
        ('margin-left', 'auto'),
        ('margin-right', 'auto')
    ]
},



]



)

In [182]:
df5 = df5.set_properties(

    subset=['name'],

    **{'font-family': 'monospace'}

)

In [183]:
df5.to_html("pokemon.html", index = False)

In [184]:
print(repr(df4.loc[0, 'type1']))  # Grass
print(repr(df4.loc[0, 'type2']))  # Poison

'Grass'
'Poison'