In [1]:
import pandas as pd

In [2]:
df = pd.read_json('../datasets/typing_data.json')

In [3]:
df.head()

,layout,textType,timeStamp,length,time,errors,speed,histogram
0,en-us,generated,2025-07-08 14:02:44+00:00,124,28310,7,262.804663,"[{'codePoint': 32, 'hitCount': 24, 'missCount'..."
1,en-us,generated,2025-07-08 14:03:13+00:00,120,28309,8,254.336077,"[{'codePoint': 32, 'hitCount': 20, 'missCount'..."
2,en-us,generated,2025-07-08 14:03:42+00:00,118,26795,7,264.228401,"[{'codePoint': 32, 'hitCount': 18, 'missCount'..."
3,en-us,generated,2025-07-08 14:05:21+00:00,117,26945,8,260.530711,"[{'codePoint': 32, 'hitCount': 17, 'missCount'..."
4,en-us,generated,2025-07-08 14:05:51+00:00,125,29252,10,256.392725,"[{'codePoint': 32, 'hitCount': 18, 'missCount'..."

In [4]:
df

,layout,textType,timeStamp,length,time,errors,speed,histogram
0,en-us,generated,2025-07-08 14:02:44+00:00,124,28310,7,262.804663,"[{'codePoint': 32, 'hitCount': 24, 'missCount'..."
1,en-us,generated,2025-07-08 14:03:13+00:00,120,28309,8,254.336077,"[{'codePoint': 32, 'hitCount': 20, 'missCount'..."
2,en-us,generated,2025-07-08 14:03:42+00:00,118,26795,7,264.228401,"[{'codePoint': 32, 'hitCount': 18, 'missCount'..."
3,en-us,generated,2025-07-08 14:05:21+00:00,117,26945,8,260.530711,"[{'codePoint': 32, 'hitCount': 17, 'missCount'..."
4,en-us,generated,2025-07-08 14:05:51+00:00,125,29252,10,256.392725,"[{'codePoint': 32, 'hitCount': 18, 'missCount'..."
...,...,...,...,...,...,...,...,...
111,en-us,generated,2026-04-28 16:39:33+00:00,116,29228,4,238.127823,"[{'codePoint': 32, 'hitCount': 12, 'missCount'..."
112,en-us,generated,2026-04-28 16:40:03+00:00,113,27440,7,247.084548,"[{'codePoint': 32, 'hitCount': 11, 'missCount'..."
113,en-us,generated,2026-04-28 16:40:39+00:00,113,33150,5,204.524887,"[{'codePoint': 32, 'hitCount': 12, 'missCount'..."
114,en-us,generated,2026-04-28 16:41:12+00:00,119,29358,4,243.204578,"[{'codePoint': 32, 'hitCount': 12, 'missCount'..."
115,en-us,generated,2026-04-28 16:41:43+00:00,112,29249,5,229.751444,"[{'codePoint': 32, 'hitCount': 12, 'missCount'..."

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   layout     116 non-null    object
 1   textType   116 non-null    object
 2   timeStamp  116 non-null    datetime64[ns, UTC]
 3   length     116 non-null    int64
 4   time       116 non-null    int64
 5   errors     116 non-null    int64
 6   speed      116 non-null    float64
 7   histogram  116 non-null    object
dtypes: datetime64[ns, UTC](1), float64(1), int64(3), object(3)
memory usage: 7.4+ KB

In [6]:
df.describe()

           length          time      errors       speed
count  116.000000    116.000000  116.000000  116.000000
mean   116.568966  31748.560345    6.836207  222.651402
std      3.165642   3432.332963    2.734463   23.011454
min    111.000000  25138.000000    1.000000  162.824173
25%    114.000000  29015.750000    5.000000  205.198033
50%    116.000000  31614.000000    7.000000  221.618140
75%    118.000000  33938.250000    8.000000  239.350494
max    125.000000  42377.000000   16.000000  275.958840

In [11]:
df['histogram'][0]

[{'codePoint': 32, 'hitCount': 24, 'missCount': 1, 'timeToType': 169},
 {'codePoint': 97, 'hitCount': 18, 'missCount': 1, 'timeToType': 186},
 {'codePoint': 101, 'hitCount': 27, 'missCount': 2, 'timeToType': 184},
 {'codePoint': 105, 'hitCount': 12, 'missCount': 0, 'timeToType': 235},
 {'codePoint': 108, 'hitCount': 10, 'missCount': 0, 'timeToType': 253},
 {'codePoint': 110, 'hitCount': 15, 'missCount': 2, 'timeToType': 209},
 {'codePoint': 114, 'hitCount': 17, 'missCount': 1, 'timeToType': 253}]